openapi: 3.0.1
info:
  title: API exo 6
  version: 1.0.0
servers:
  - url: 'https://localhost:8000'
paths:
  /uesrs/{id}:
components:
  schemas:
    PersonalInfo:
      type: object
      properties:
        first_name:
          type: string
        last_name: 
          type: string
        birthdate: 
          type: string
        email:
          type: string
    Address:
      type: object
      properties:
        address_street:
          type: string
        address_city:
          type: string
        address_country:
          type: string
        address_postal_code:
          type: string
    Preferences:
      type: object
      properties:
        needs_newsletter:
          type: boolean
        language:
          type: string
          enum:
            - mg
            - fr 
            - eng
    CreateUserProfile:
      allOf:
        - $ref: '#/components/schemas/PersonalInfo'
        - $ref: '#/components/schemas/Preferences'
        - $ref: '#/components/schemas/Address'
    UserProfile:
      allOf:
        - $ref: '#/components/schemas/CreateUserProfile'
      type: object
      properties:
        identifier:
          type: string